using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Text;
using System.Text.RegularExpressions;

namespace NexusJobs
{
    public partial class ClientJobs : System.Web.UI.Page
    {
        string strClientId = null;
        string strClientName = null;
        string strJobStatus = null;
        string strClientType = null;
        string StrQuery = null;
        string cstext1 = null;
        string[] strArrUser = null;
        public static string prevPage = null;
        BLmodel BL = new BLmodel();

        protected void Page_Load(object sender, EventArgs e)
        {
            string strUser = (string)Session["ssUser"];

            if (!string.IsNullOrEmpty(strUser))
            {
                strArrUser = strUser.Split('&');
            }
            else
            {
                Response.Redirect("Login.aspx");
            }

            DataTable dtClientDetails = new DataTable();
            strClientId = Session["ssClientId"].ToString();
            strClientName = Session["ssClientName"].ToString();
            strJobStatus = Session["ssJobStatus"].ToString();
            strClientType = Session["ssClientType"].ToString();

            lbClientName.Text = Session["ssClientName"].ToString();
            lbClientType.Text = Session["ssClientType"].ToString();
            StrQuery = "select top 15 jld.fkey_client as 'FKey' ,job_Name as 'MethodName' ,Method_Status as Status ,LastRunDate ,NextRunDate ,Comments from JMC_LOGDETAILS jld left join JMC_METHODS jm on jm.pkey = jld.fKey_Methods inner join jmc_clients jc on jc.pkey = jld.fkey_client where jc.ClientName = '" + Session["ssClientName"].ToString() + "' Order by Jld.pkey desc";
            LoadClientDetails(BL.returnDataTable(StrQuery));

            if (!IsPostBack)
            {
                //prevPage = Request.UrlReferrer.ToString();
            }
        }

        private void LoadClientDetails(DataTable dtTable)
        {
            rptTable.DataSource = dtTable;
            rptTable.DataBind();
        }

        protected void rptTable_ItemCommand(object source, RepeaterCommandEventArgs e)
        {
            if (e.CommandName.Equals("commJobStatus"))
            {
                Session["ssScreenType"] = 2;
                Session["ErrorclientName"] = Session["ssClientName"].ToString();
                Session["ErrorClientId"] = Session["ssClientId"].ToString();
                Session["ErrorClientType"] = Session["ssClientType"].ToString();
                Session["ErrorJobStatus"] = Session["ssJobStatus"].ToString();
                Response.Redirect("JobStatus.aspx");
            }
        }

        protected void rptTable_ItemDataBound(object sender, RepeaterItemEventArgs e)
        {

            foreach (RepeaterItem rp in rptTable.Items)
            {

                LinkButton lnkValues = (LinkButton)rp.FindControl("lnkJobStatus");

                if (lnkValues.Text == "Success")
                {
                    lnkValues.ForeColor = System.Drawing.Color.Green;
                }
                else if (lnkValues.Text == "Running")
                {
                    lnkValues.ForeColor = System.Drawing.Color.Orange;
                }
                else if (lnkValues.Text == "Failed")
                {
                    lnkValues.ForeColor = System.Drawing.Color.Red;
                }
            }
        }


        protected void lnkPrevious_Click1(object sender, EventArgs e)
        {
            Response.Redirect("JobDetails.aspx");
        }

        protected void imgbtHome_Click1(object sender, ImageClickEventArgs e)
        {
            Response.Redirect("Dashboard.aspxk");
        }

        protected void lnkExportExcel_Click(object sender, EventArgs e)
        {
            if (rptTable.Items.Count <= 0)
            {
                RegisterStartupScript("MSG", "<script>alert ('No Records to Export!')</script>;");
                return;
            }
            ExportToExcel(BL.returnDataTable(StrQuery));
        }

        //Exporting to Excel
        public void ExportToExcel(DataTable dt)
        {

            if (dt.Rows.Count > 0)
            {

                string filename = "ClientJobs.xls";

                string excelHeader = "Report generated by :" + strArrUser[0].ToString() + " ";

                System.IO.StringWriter tw = new System.IO.StringWriter();

                System.Web.UI.HtmlTextWriter hw = new System.Web.UI.HtmlTextWriter(tw);

                DataGrid dgGrid = new DataGrid();

                dgGrid.DataSource = dt;

                dgGrid.DataBind();

                dgGrid.HeaderStyle.BackColor = System.Drawing.Color.LightBlue;
                dgGrid.HeaderStyle.Font.Bold = true;
                dgGrid.GridLines = GridLines.Both;

                // Report Header

                /*arivu*/
                hw.WriteLine("<table>");
                hw.WriteLine("<tr><td><b><u><font size=’3′> " + excelHeader + " </font></u></b></td></tr>");
                hw.WriteLine("<tr><td><b><u><font size=’3′> " + "Client Type:" + lbClientType.Text.ToUpper() + " </font></u></b></td><td><b><u><font size=’3′> " + "Client Name:" + lbClientName.Text.ToUpper() + " </font></u></b></td>");
                hw.WriteLine("</table>");
                /**/

                //Get the HTML for the control.
                dgGrid.RenderControl(hw);

                Response.ContentType = "application/vnd.ms-excel";
                Response.AppendHeader("Content-Disposition", "attachment; filename=" + filename + "");

                //this.EnableViewState = false;
                Response.Write(tw.ToString());
                Response.End();

            }

        }

        #region Show Limitted Content //arivu
        //Show Limitted Content
        protected string ShowContent(object o)
        {
            int iStringSize = 50;
            string content = string.Empty;
            if (o.ToString().Length > iStringSize)
            {
                content = Regex.Replace(o.ToString(), "<(.|\n)*?>", string.Empty).Replace("&nbsp;", string.Empty);
                if (content.Length >= iStringSize)
                {
                    content = content.Substring(0, iStringSize);
                    //content = content.Substring(0, content.LastIndexOf(" ")); //removes last word
                }
            }
            else
            {
                content = o.ToString();
            }
            return content;
        }
        #endregion
        #region MakeLink //arivu
        // Generate link for Readmore
        protected string MakeLink(object o, int iRowId)
        {
            string content = o.ToString();
            string url = string.Empty;
            if (content.Length > 50)
            {
                if (!string.IsNullOrEmpty(content))
                {
                    url = "<a  id=\"various" + iRowId + "\" href=\"#inline" + iRowId + "\"  >Readmore</a>";
                }
                else
                {
                    url = string.Empty;
                }
            }

            return url;
        }
        #endregion
        #region CreateHiddenField //arivu
        //Store values into Hidden field, which will be displayed when link is clicked.
        protected string CreateHiddenField(object o, int RowID)
        {
            string content = string.Empty;
            string value = string.Empty;

            if (!string.IsNullOrEmpty(o.ToString()))
            {
                content = Regex.Replace(o.ToString(), "'", string.Empty).Replace("&nbsp;", string.Empty);
            }

            if (o.ToString().Length > 50)
            {
                value = "<div style=\"display: none;\">";
                value += "<div id=\"inline" + RowID + "\" style=\"margin: 10px;width:600px;height:200px;overflow:auto;font-family: Verdana, Geneva, sans-serif; font-size: 12px;\">";
                value += content;
                value += "</div>";
            }
            return value;
        }
        #endregion
        #region Makescript //arivu
        //Generate Javascript for Readmore links
        protected string MakeScript(int RowId)
        {
            string Script = string.Empty;

            Script = "<script type=\"text/javascript\">";
            Script += "$(document).ready(function() {";
            Script += "$(\"#various" + RowId + "\").fancybox({";
            Script += "	'titlePosition'		: 'inside',";
            Script += "	'transitionIn'		: 'none',";
            Script += "	'transitionOut'		: 'none'";
            Script += "});";
            Script += "});";
            Script += "</script>";
            return Script;
        }
        #endregion
    }
}